name: Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - id: go-cache-paths
        run: |
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

      - name: Go Build Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ github.sha }}
          restore-keys: ${{ runner.os }}-go-build-

      - name: Go Mod Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-mod-

      - name: Set up environment
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-I$(python3-config --includes)" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L$(python3-config --prefix)/lib -lpython3.12" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$(python3-config --prefix)/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Run tests
        run: go test ./... -cover

